### PR TITLE
modules/openstack: etc port count based on etc node count

### PR DESCRIPTION
**Pull request by jstuever**
The port count was previously using the worker nodes value instead of
the etcd nodes value.

### CODE REVIEW

**Comment by jstuever** [comment]
@flaper87 This is to resolve the following error. Plus, it makes the etcd port count equal to the number of etcd nodes. I believe we need to at least merge the etcd port change.
```
data.openstack_compute_flavor_v2.etcd_flavor: Refreshing state...
Error: Error running plan: 1 error(s) occurred:
* module.etcd.openstack_compute_instance_v2.etcd_conf: 1 error(s) occurred:
* module.etcd.openstack_compute_instance_v2.etcd_conf: Resource 'data.null_data_source.networks' not found for variable 'data.null_data_source.networks.outputs'
```

**Comment by flaper87** [comment]
The PR looks good but I think we may need to find a different solution. The reason we're using the `null_data_source` is that users can input their own networks. I believe this might not be implemented yet. In other words, in addition to the port that we're assigning users may decide to attach more networks and we need to generate an array to pass to the instance creation. We're creating that array using the `null_data_source`.

Does this happen when count is 0?

**Comment by jstuever** [comment]
@flaper87 Oh, I see what's it's doing now... let me play with it some more and see if I can make sense of it. We still need to match etcd port count to etcd count, right? I can submit a separate PR for that.

**Comment by jstuever** [comment]
@flaper87 It happens when the count is greater than 1. Everything works just fine if there is only 1 of each master, etcd, and worker node.

**Comment by jstuever** [comment]
@flaper87 I scaled this back to only handle the etcd port count issue. Something is still very wrong with mapping when nodes > 1. I'll submit another PR if I can find a solution there.

**Comment by flaper87** [comment]
The main PR has been merged. We can now send individual PRs to the installer

**Pull request closed without merging**
