### PR TITLE
[WIP] *openstack: use a shared provider file in steps

### PR DESCRIPTION
**Pull request by jstuever**
The passing of provider configurations to the individual modules was
cumbersome. Having to re-define the provider for each step is equally
so. This solution is to use a shared file defining the provider for all
of the OpenStack steps.

### CODE REVIEW

**Comment by jstuever** [comment]
This also fixes a bug in the last PR... where modules/openstack/vpc wasn't moved properly.

**Comment by flaper87** [comment]
I'm a bit unsure about this change. My understanding is that modules should be independent of the steps and we should be able to run them standalone. With this change, we'll depend on the steps to create the provider instance that will be consumed by the module later on.

Admittedly, all of our steps (except for `asset`, for now) depend on a provider but the dependency is introduced by the module, not the step.

**Comment by jstuever** [comment]
I was basing this on the AWS code. It is a little different in that they include the provider via modules/aws/target-defaults in each of the steps and then include the primary modules. I had planned on creating symlinks to a file that referenced target-defaults the same as AWS. Then I realized I could skip the middle-man and just put the provider in the symlink file. One thing to keep in mind: I believe we get an error if we include the provider more than once (such as if we were to use more than one module each setting their own). I could be wrong.

Having said that, 3 options present themselves...
- leave it as was... providers in modules (still need to move the modules/vpc files to topology)
- mimic the AWS bits using target-defaults
- push forward with this PR.

**Comment by jstuever** [comment]
Reading up on https://www.terraform.io/docs/modules/usage.html

**Comment by jstuever** [comment]
@flaper87 After researching the topic, I continue to believe this PR is the way to go. In the documentation [implicit-provider-inheritance](https://www.terraform.io/docs/modules/usage.html#implicit-provider-inheritance) it is "recommended in the common case where only a single configuration is needed for each provider across the entire configuration." It is parallel to what they are doing in [steps/assets/aws](https://github.com/flaper87/installer/blob/master/steps/topology/aws/main.tf#L6) except we are leveraging reusable code. We can always remove the symlink in steps where the provider is not needed. In addition, we can [pass-providers-explicitly](https://www.terraform.io/docs/modules/usage.html#passing-providers-explicitly) in cases where the default one is not appropriate. Plus, it makes for much cleaner code. I've made my case; I support whichever decision you make.

**Comment by flaper87** [comment]
The main PR has been merged. We can now send individual PRs to the installer.

**Pull request closed without merging**
