### PR TITLE
*/openstack: organize variables and terraform fmt.

### PR DESCRIPTION
**Pull request by jstuever**
Tidy up the OpenStack code and ensure it passes the ci tests when submitted upstream.
- Renamed modules/openstack/master-asg -> masters.
- Renamed modules/openstack/worker-asg -> workers.
- Renamed modules/openstack/vpc -> topology.
- Alphabetized or otherwise organized most variables.
- Applied "terraform fmt" to all associated .tf files.

### CODE REVIEW

**Comment by jstuever** [comment]
I apologize in advance for all of the re-factoring that will be required based on this PR.

**Comment by jstuever** [comment]
@flaper87 I've got two more PRs lined up based on this one. Once it's merged I'll submit them.

**Comment by flaper87** [comment]
Thanks, @jstuever 

This looks good to me. @tomassedovic since you're now looking into the LB stuff, you may want to check this PR as it renames some of the LB variables. We can merge this now since the LB implementation is still in an early stage.

**Comment by tomassedovic** [comment]
I sure wish I'd looked at this PR before fixing the loadbalancer stuff and pushing it to this branch.

I think it might be easier if I revert the four new commits that conflict with this and update those myself rather than have @jstuever update this massive patch.

@flaper87 @jstuever what do you think?

**Comment by tomassedovic** [comment]
Yep, I was totally being to hasty with pushing this. If y'all agree, I'll revert my commits, push them to `openstack-lb` and once this merges rebase that branch.

**Comment by jstuever** [comment]
@tomassedovic I would prefer that.... I don't have access to a stack environment with LBaaS and so it will be difficult to test the new code changes after resolving conflicts.

**Comment by jstuever** [comment]
Or, I can do the work but someone else will have to test it.

**Comment by tomassedovic** [comment]
yeah no that's fair. I'll revert my changes and rebase on top of ours. The LB stuff actually needs more work than I thought so I'm okay with this.

**Comment by jstuever** [comment]
@tomassedovic You might want to wait for my next PR too... It consolidates how we we handle the provider authentication. I'm waiting for this to merge so I can submit it.

**Comment by jstuever** [comment]
https://github.com/jstuever/openshift-installer/commits/openstack-sharedprovider

**Comment by tomassedovic** [comment]
@jstuever done, feel free to propose the other one

**Pull request merged**
